// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var ctx;
    ctx = window;
    ctx.ux = new Civ.UI.UXController;
    ctx.world = new Civ.HexWorld({
      size: 40,
      ux: ux
    });
    world.buildHexesInGrid();
    ctx.worldView = new Civ.UI.HexWorldView({
      model: world,
      ux: ux
    });
    worldView.render();
    ctx.civ = new Civ.Civilization({
      name: "Egyptians"
    });
    ctx.unit = new Civ.SettlerUnit({
      hex: world.root,
      civ: civ
    });
    ctx.human = new Civ.HumanPlayer({
      civ: civ
    });
    ctx.game = new Civ.Game({
      players: [human]
    });
    return new Civ.UI.HumanController({
      humanPlayer: human,
      ux: ux,
      game: game
    });
  });

}).call(this);
