// Generated by CoffeeScript 1.3.3
(function() {
  var connect;

  connect = require('connect');

  connect.createServer(connect["static"](__dirname)).listen(9191);

  console.log("Started static server on 9191");

}).call(this);
